name: Remove Ready Label

on:
  pull_request:
    types: [synchronize]  # This triggers when new commits are pushed to a PR

jobs:
  remove-ready-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check and remove ready label
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const hasReadyLabel = labels.some(label => label.name === 'ready');
            
            if (hasReadyLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: ['ready']
              });
            }
